{{- $redisPass := include "sentry.redis.password" . -}}
{{- if .Values.snuba.transactionsCleanup.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-transactions-cleanup
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "{{ .Values.snuba.transactionsCleanup.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
            checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.transactionsCleanup.annotations }}
{{ toYaml .Values.snuba.transactionsCleanup.annotations | indent 12 }}
        {{- end }}
          labels:
            app: {{ template "sentry.fullname" . }}
            release: "{{ .Release.Name }}"
            {{- if .Values.snuba.transactionsCleanup.podLabels }}
{{ toYaml .Values.snuba.transactionsCleanup.podLabels | indent 12 }}
            {{- end }}
        spec:
          affinity:
            {{- if .Values.snuba.transactionsCleanup.affinity }}
{{ toYaml .Values.snuba.transactionsCleanup.affinity | indent 12 }}
            {{- end }}
            {{- if .Values.snuba.transactionsCleanup.nodeSelector }}
          nodeSelector:
{{ toYaml .Values.snuba.transactionsCleanup.nodeSelector | indent 12 }}
            {{- end }}
            {{- if .Values.snuba.transactionsCleanup.tolerations }}
          tolerations:
{{ toYaml .Values.snuba.transactionsCleanup.tolerations | indent 12 }}
            {{- end }}
            {{- if .Values.images.snuba.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 12 }}
            {{- end }}
          restartPolicy: Never
          containers:
          - name: {{ .Chart.Name }}-snuba-transactions-cleanup
            image: "{{ template "snuba.image" . }}"
            imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
            command: ["snuba"]
            args:
              - cleanup
              - --storage
              - transactions
              - --dry-run
              - "False"
              - --log-level
              - {{ .Values.snuba.logging.level }}
            env:
              - name: SNUBA_SETTINGS
                value: docker
              - name: SENTRY_EVENT_RETENTION_DAYS
                value: {{ .Values.sentry.eventRetentionDays | quote }}
              - name: CLICKHOUSE_SINGLE_NODE
                value: {{ if .Values.externalClickhouse.clusterName }}"false"{{ else }}"true"{{end}}
              {{- if .Values.metrics.enabled }}
              - name: DOGSTATSD_HOST
                value: "{{ template "sentry.fullname" . }}-metrics"
              - name: DOGSTATSD_PORT
                value: "9125"
              {{- end}}
              - name: DEFAULT_BROKERS
                value: {{ include "sentry.kafka.bootstrappers" . | quote }}
              - name: SENTRY_DSN
                value: {{ .Values.snuba.sentryDsn | quote }}
              - name: CLICKHOUSE_HOST
                value: {{ include "sentry.clickhouse.host" . | quote }}
              - name: REDIS_HOST
                value: {{ include "sentry.redis.host" . | quote }}
              - name: REDIS_PORT
                value: {{ include "sentry.redis.port" . | quote }}
              {{- if $redisPass }}
              - name: REDIS_PASSWORD
                value: {{ $redisPass | quote }}
              {{- end }}
{{- if .Values.snuba.transactionsCleanup.env }}
{{ toYaml .Values.snuba.transactionsCleanup.env | indent 8 }}
{{- end }}
            volumeMounts:
            - mountPath: /etc/snuba
              name: config
              readOnly: true
            resources:
{{ toYaml .Values.snuba.transactionsCleanup.resources | indent 14 }}
          volumes:
            - name: config
              configMap:
                name: {{ template "sentry.fullname" . }}-snuba

{{- end }}
