apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-api
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}
      release: "{{ .Release.Name }}"
      role: snuba-api
{{- if not .Values.snuba.api.autoscaling.enabled }}
  replicas: {{ .Values.snuba.api.replicas }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.api.annotations }}
{{ toYaml .Values.snuba.api.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-api
        {{- if .Values.snuba.api.podLabels }}
{{ toYaml .Values.snuba.api.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.api.affinity }}
{{ toYaml .Values.snuba.api.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.api.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.api.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.api.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.api.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        args:
          - api
          - --log-level
          - {{ .Values.snuba.logging.level }}
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
        - name: SNUBA_SETTINGS
          value: docker
        - name: SENTRY_EVENT_RETENTION_DAYS
          value: {{ .Values.sentry.eventRetentionDays | quote }}
        - name: CLICKHOUSE_SINGLE_NODE
          value: {{ if .Values.externalClickhouse.clusterName }}"false"{{ else }}"true"{{end}}
        {{- if .Values.metrics.enabled }}
        - name: DOGSTATSD_HOST
          value: "{{ template "sentry.fullname" . }}-metrics"
        - name: DOGSTATSD_PORT
          value: "9125"
        {{- end}}
        - name: DEFAULT_BROKERS
          value: {{ include "sentry.kafka.bootstrappers" . | quote }}
        - name: SENTRY_DSN
          value: {{ .Values.snuba.sentryDsn | quote }}
        - name: CLICKHOUSE_HOST
          value: {{ include "sentry.clickhouse.host" . | quote }}
        - name: REDIS_HOST
          value: {{ include "sentry.redis.host" . | quote }}
        - name: REDIS_PORT
          value: {{ include "sentry.redis.port" . | quote }}
{{- if .Values.snuba.api.env }}
{{ toYaml .Values.snuba.api.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: {{ template "snuba.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.snuba.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: {{ template "snuba.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.snuba.api.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.snuba.api.resources | indent 10 }}
{{- if .Values.snuba.api.sidecars }}
{{ toYaml .Values.snuba.api.sidecars | indent 6 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.api.volumes }}
{{ toYaml .Values.snuba.api.volumes | indent 8 }}
{{- end }}
